apiVersion: v1
kind: pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
    - name: course
      ValueFrom:
        ConfigMapKeyRef:
          name: kumarsiva.shop
          key: course
    - name: trainer
      ValueFrom:
        ConfigMapKeyRef:
          name: kumarsiva.shop
          key: trainer