apiVersion: v1
kind: service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
    protocol: TCP
    port: 80
    targetport: 80
    nodeport: 32755